### ISSUE TITLE
Color palette too bright

### ISSUE THREAD

**Issue by toddocon** [Autodesk/hubble#15]
Can the prior collaboration graph color pallet be used? The new pallet is rather bright.

**Comment by pluehne** [comment]
I adapted the color palette from Eventbrite’s [BrightCharts](http://eventbrite.github.io/britecharts/tutorial-donut.html) as a base for all charts. I want the color palette to be consistent, which is why I applied it to the collaboration chart before the GitHub Universe presentation.

Aside from that, Eventbrite did a much better job at creating a nice color palette than D3 (which provided the [color palette we used earlier](https://bl.ocks.org/pstuffa/3393ff2711a53975040077b7453781a9)) in my humble opinion. To my mind, their color scheme is not well balanced and contains many colors that don’t fit the rest of Hubble’s Dashboard well (for instance, the brown, pink, yellow/ochre, gray, and green tones).

For this reason, I’d like to keep the color palette as is for the time being. I hope you’re not upset about this, but I really want to maintain a high level of consistency throughout the dashboard.

**Comment by larsxschneider** [comment]
## Previous Colors

<img width="717" alt="screen shot 2017-10-15 at 10 23 26" src="https://user-images.githubusercontent.com/477434/31587233-fa5b7156-b192-11e7-8cb4-453c41fa7deb.png">
<img width="735" alt="screen shot 2017-10-15 at 10 23 35" src="https://user-images.githubusercontent.com/477434/31587234-fe99dbea-b192-11e7-962e-87c5a93fc9cf.png">

**Comment by larsxschneider** [comment]
## Current Colors
<img width="731" alt="screen shot 2017-10-15 at 10 22 08" src="https://user-images.githubusercontent.com/477434/31587241-27e2a31a-b193-11e7-9b6d-d6c99836c82b.png">
<img width="742" alt="screen shot 2017-10-15 at 10 22 24" src="https://user-images.githubusercontent.com/477434/31587243-3549ab20-b193-11e7-8556-f1bf7fd50ac4.png">

**Comment by larsxschneider** [comment]
@pluehne @craigez @toddocon @rashamalek @jonico @acrlewis @djdefi @kai @stoe : Let's vote 🎉 ! If you have time and interest, please use the [reactions buttons](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) on the two comments above to indicate what color scheme you like better (until Tuesday, Oct 17).

**Comment by pluehne** [comment]
## Color Palette of Existing Charts

![screenshot from 2017-10-15 19-34-57](https://user-images.githubusercontent.com/3244280/31587318-fb7d67ea-b1df-11e7-8825-5b161a9c45d7.png)

**Comment by acrlewis** [comment]
> not well balanced and contains many colors that don’t fit the rest of Hubble’s Dashboard
💯

**Comment by larsxschneider** [comment]
3 votes for the new colors against 2 votes for the old colors.
That means we leave it as is until we get a PR with an further improved color scheme 😄

**Comment by kai** [comment]
@larsxschneider It's a little late but I just added my 👍  to the existing (old) colour palette.
