### ISSUE TITLE
How to make hubble work for an org on github.com?

### ISSUE THREAD

**Issue by spier** [Autodesk/hubble#202]
Hi.

I have been working on a way to visualize contributions between different teams/repos in our GitHub org.

When I found https://autodesk.github.io/hubble/, it seemed very related to my idea, however much more focused on multiple orgs (rather than teams), and of course only for GitHub Enterprise Server.

I was wondering:

* Would it be a huge undertaking to make hubble work with GitHub Enterprise Cloud, i.e. an org that runs fully on github.com, rather than on-premise? 
* Where would I start, if I wanted to do this?

Cheers
/Sebastian

**Comment by pluehne** [comment]
@spier: I’m glad you find Hubble an interesting project :slightly_smiling_face:. Unfortunately, supporting GitHub Enterprise Cloud would be a difficult undertaking right now.

The reason for that is that the majority of the data that Hubble collects isn’t available through official GitHub API endpoints (have a look at [some of Hubble’s data collection scripts](https://github.com/Autodesk/hubble/tree/master/updater/scripts) to get an idea). Instead, Hubble relies on techniques such as database querying and log parsing performed *directly on the GitHub Enterprise Server* to get the data it needs. Doing so isn’t an option on GitHub Enterprise Cloud because GitHub won’t give you SSH access to the GitHub.com servers :slightly_smiling_face:.

So unless GitHub changes its plans and make official API endpoints for retrieving all of our metrics available (at least a significant fraction of those), there is nothing we can do to provide Hubble for your GitHub.com organization :slightly_frowning_face:. And to my knowledge, GitHub hasn’t shared any specific plans for more powerful administrator APIs on GitHub Enterprise Cloud.

**Comment by spier** [comment]
@pluehne thanks for the amazingly fast reply!

I see. That sounds like a long stretch indeed then (or impossible at worst). I should really ask my GitHub Sales rep for "SSH access to the GitHub.com servers" but I am pretty sure you are right and they will say no HAHA :)

The data that I have used so far is based on inter-team pull requests. So at the very least I might take inspiration from the visualization below, and see if that shows interesting relationships on a team-2-team level as well.

<img width="706" alt="Screen Shot 2020-02-02 at 15 39 46 " src="https://user-images.githubusercontent.com/163029/73609909-5f260f80-45d2-11ea-9fe5-73db556bd9ca.png">

Thanks again for the reply!

**Comment by pluehne** [comment]
@spier: You’re welcome! Good luck asking GitHub for SSH access :grin:.

While it would be possible to provide a version of Hubble that’s restricted to metrics that we can retrieve from GitHub Enterprise Cloud, that would be a huge effort right now for little value (as only a few charts would remain available). Unfortunately, [the particular chart you were interested in requires SQL database calls](https://github.com/Autodesk/hubble/blob/master/updater/reports/ReportOrgCollaboration.py), so that one will be hard to reproduce exactly as is in any case. But feel free to be inspired by that chart or steal the JavaScript portion of that chart at least :+1:.

I’ll mark this ticket as *closed,* as there’s nothing we can do but wait right now, but that doesn’t mean the discussion is over. Feel free to comment if you have more questions.
