### ISSUE TITLE
Security vulnerabilities found

### ISSUE THREAD

**Issue by pranereddy** [Autodesk/hubble#205]
Hi, 
We are using hubble in our GHES, recently we got security alerts for vulnerabilities, would you please fix them by upgrading to stable versions.
![image](https://user-images.githubusercontent.com/35363673/78743674-e8fcab00-797c-11ea-9437-71c760207c9d.png)

**Comment by pluehne** [comment]
@pranereddy: I’ve updated all Node.js dependencies to their latest versions now.

Please note that security vulnerabilities in the Node.js dependencies have very low priority to us because Node.js is *only* used for unit testing. The unit tests are *never* executed in a production environment, so none of our users are affected by those.

But thanks for reporting this anyway!

**Comment by pranereddy** [comment]
@pluehne Thanks for the update and fix 🙂

**Comment by pluehne** [comment]
You’re welcome, @pranereddy!
