### ISSUE TITLE
Multiple issues after upgrade to GHES 3.0.8

### ISSUE THREAD

**Issue by toddocon** [Autodesk/hubble#231]
I see one PR in the queue to address issues after upgrading to GHES 3.0.8. I made those changes by hand but am still seeing issues running Hubble. I've attached the output for reference. 
[hubble_log.txt](https://github.com/Autodesk/hubble/files/6611187/hubble_log.txt)

**Comment by svasek** [comment]
Hi, this issue is new in 3.0.8.

**Comment by toddocon** [comment]
Yes, 3.0.8 (I updated my original post). We upgraded from 2.22.x.

**Comment by svasek** [comment]
Run the command bellow on the GitHub Enterprise server node. That should fix/workaround the issue:

> sudo usermod -aG docker git

**Comment by larsxschneider** [comment]
👋 Hi folks! Please don't change the group memberships ☝️ as this can have serious side effects on other GHES components and therefore damage your GHES instance.

**Comment by toddocon** [comment]
I worked with support. This change is not advised. This is more of an issue with ghe-dbconsole, which Hubble uses, and will be addressed in a future GHES patch release.

We're also close to having a working version of the failed webhooks report using the new log mechanism in 3.0.

**Comment by toddocon** [comment]
The Org Owners report also needs repairs. No data was collected so it might be a DB change that affected it.

**Comment by pluehne** [comment]
Sorry for the long turnaround. I believe the organization owners report to be fixed by #247. I’m not seeing any of the remaining issues on GitHub Enterprise Server 3.1 with the latest version that’s on `master` anymore (which contains #246). Please let me know if you’re still seeing issues. I’m going to close this ticket, but please reopen it if you think there’s still more to do.
